### ISSUE TITLE
Feature request: add sound only option for playback

### ISSUE THREAD

**Issue by nicman23** [Kolifanes/plugin.video.youtube#13]
The main reason for this is android. It would be nice to put kodi to background / lock the screen and still have audio for things like podcasts or other talk heavy show (ie shoddycast)

**Comment by Twilight0** [comment]
I think this feature request applies to Kodi itself not the youtube addon/plugin, so better request it there.

**Comment by h0d3nt3uf3l** [comment]
Think Twilight0 is right. The AddOn is easily said a program in kodi itself. So the youtube-addon can use the resources what kodi gives it, but can't modificate the host processes. Correct me if I'm wrong.

**Comment by nicman23** [comment]
Correct me if I am wrong, but don't you already do the same thing with the option to select the resolution? I just ask of an extra option there, where audio only plays.

Doesn'y Youtube already provide audio only streams that youtube-dl then muxxes with video anyways?

**Comment by Twilight0** [comment]
AFAIK, Youtube has never provided audio-only streams, youtube-dl always downloads streams with video, then to make it audio-only you have to demux it locally, or use an internet service like "ClipConverter" (google it).

But once again, in order to minimize Kodi, it has to be done to this host process, the add-on is written in python and communicates to the host (interpreter) for specific functions only.

I 'd suggest you to try another app that can play youtube in the background such as "Viral Playlist Video Player" which is compatible even with old Gingerbread Androids.

**Comment by nicman23** [comment]
Thanks anyways!

**Comment by disrupted** [comment]
@Twilight0 

> AFAIK, Youtube has never provided audio-only streams, youtube-dl always downloads streams with video, then to make it audio-only you have to demux it locally, or use an internet service like "ClipConverter" (google it).

that's not correct. if you run `youtube-dl -F <url-to-video>` you can see plenty of audio-only streams. the problem is that Kodi doesn't support DASH afaik.

**Comment by nicman23** [comment]
that makes a ton of sense. I was about to write about these streams that yotuube-dl reports and how it muxes the 2 streams into 1 file/ stream/ pipe.

But yes if kodi does not support dash that is a whole another issue :P

**Comment by h0d3nt3uf3l** [comment]
Maybe if Inputstream is implemented in the AddOn its possible to separate the audio and video-stream. But its only a thought of an uniformed :)
