### ISSUE TITLE
Subtitles 

### ISSUE THREAD

**Issue by frenchdj** [Kolifanes/plugin.video.youtube#40]
Hello, my name is João, i´m from portugal and i made 3 addons that only works with your pluggin. In one of my addons i´ve adden documentarys that needs subtitles. It works fine if the subtitle in portuguese is hardcoded in the video, but, if its not it doens´t apear in the video on kodi. Can you add subtitle item on the addon? 
Hope you understand my issue. Sorry my bad english
Thanks a lot for the great plugin

**Comment by h0d3nt3uf3l** [comment]
Hi João,
this might be a problem because we can only play the videos via the player of kodi. I know that ffmpeg (the programm which are the player based on) support such an funciton. Sadly I don't know if the player this can do. Maybe we're able to get this included with inputstream (an available plugin in kodi v17 (krypton)).

I see what I can do.

**Comment by mac1202** [comment]
maybe you can have a look at the youtube-dl [source,](https://github.com/rg3/youtube-dl/tree/381ff44756ecf188de476a7a4cc9d4becf6633d1) as support youtube subtitle.
Here is a example output of mpv (that use youtube-dl for playing youtube url)

```
mpv https://www.youtube.com/watch\?v\=rlJTnzyCKEA
[cplayer] Run command: sub-add, flags=0, args=[https://www.youtube.com/api/timedtext?v=rlJTnzyCKEA&name=&fmt=vtt&lang=en, auto, vtt, en]
[ffmpeg] Opening https://www.youtube.com/api/timedtext?v=rlJTnzyCKEA&name=&fmt=vtt&lang=en
[ffmpeg] Mime-type: 'text/vtt; charset=UTF-8'
[lavf] Found 'webvtt' at score=100 size=2048.
[demux] Detected file format: webvtt (libavformat)
[cplayer] Run command: sub-add, flags=0, args=[https://www.youtube.com/api/timedtext?v=rlJTnzyCKEA&name=&fmt=vtt&lang=fi, auto, vtt, fi]
[ffmpeg] Opening https://www.youtube.com/api/timedtext?v=rlJTnzyCKEA&name=&fmt=vtt&lang=fi
[ffmpeg] Mime-type: 'text/vtt; charset=UTF-8'
[lavf] Found 'webvtt' at score=100 size=2048.
[demux] Detected file format: webvtt (libavformat)
[cplayer] Run command: sub-add, flags=0, args=[https://www.youtube.com/api/timedtext?v=rlJTnzyCKEA&name=&fmt=vtt&lang=de, auto, vtt, de]
[ffmpeg] Opening https://www.youtube.com/api/timedtext?v=rlJTnzyCKEA&name=&fmt=vtt&lang=de
[ffmpeg] Mime-type: 'text/vtt; charset=UTF-8'
[lavf] Found 'webvtt' at score=100 size=2048.
[demux] Detected file format: webvtt (libavformat)
[cplayer]      Subs  --sid=1 --slang=en 'vtt' (webvtt) (external)
[cplayer]      Subs  --sid=2 --slang=fi 'vtt' (webvtt) (external)
[cplayer]      Subs  --sid=3 --slang=de 'vtt' (webvtt) (external)
```

**Comment by jdf76** [comment]
It’s not as simple as it looks. #1 you have to look at the code from youtube-dl. Is it written completely in python, plugins for Kodi have to be completely in python as far as I know. 

#2, we have 2 other pressing issues that need to be fixed before this Feature can be added.

#3 Both h0d3nt3uf3l http://forum.kodi.tv/member.php?action=profile&uid=319537 and I are working on other projects for work and since h0d3nt3uf3l http://forum.kodi.tv/member.php?action=profile&uid=319537 is the main project maintainer at the moment, i help with I can. We has time he’s got other things he’s working on.

What i’m boiling down to is you will have to be patient with us. It’s not going to happen over night.

One thing you may want to do, and this is a suggestion not an order, is fork the plugin from github and work on the subtitle part yourself. it’s ok if you aren’t a coder but dabble in python, if you’re interested in learning python this may be a good start. This is a very popular project so feel free to tackle it if you fee like it. 

Thanks
Jeff

**Comment by h0d3nt3uf3l** [comment]
@mac1202 is this from the youtube-dl plugin of Kodi or the youtube-dl as itself?
Think to implement it in Kodi its maybe not possible for us without sample-code.

**Comment by mac1202** [comment]
it s from youtube-dl as itself, the youtube-dl plugin of Kodi doesn't support subtitle yet.

**Comment by h0d3nt3uf3l** [comment]
Then we dont have a change because we only parse the video to the kodi player.

**Comment by Uukrull** [comment]
The subtitles can be downloaded easily.

For example, for this [video](https://www.youtube.com/watch?v=MD25QKh6mGA) we can get the list of available subtitles with http://video.google.com/timedtext?v=MD25QKh6mGA&type=list and download the english subtitle with https://www.youtube.com/api/timedtext?v=MD25QKh6mGA&fmt=vtt&lang=en

edit: I did a quick hack and this works for english subtitles

```
diff --git a/resources/lib/kodion/impl/xbmc/xbmc_items.py b/resources/lib/kodion/impl/xbmc/xbmc_items.py
index d7e847f..52c8897 100755
--- a/resources/lib/kodion/impl/xbmc/xbmc_items.py
+++ b/resources/lib/kodion/impl/xbmc/xbmc_items.py
@@ -23,6 +23,10 @@ def to_video_item(context, video_item):

     item.setProperty(u'IsPlayable', u'true')

+    video_id = context.get_param('video_id')
+    url = ("https://www.youtube.com/api/timedtext?v=%s&fmt=vtt&lang=en" % (video_id))
+    item.setSubtitles([url])
+
     _info_labels = info_labels.create_from_item(context, video_item)

     # This should work for all versions of XBMC/KODI.

```

**Comment by mac1202** [comment]
Nice maybe you could create a PR with your work so It could be integrated in the plugin.
